# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb0f7c4f1102805766ebe1c10b47d602e8d24daf0c3be8365aeec32cae693338191d18148c6879b6d0a383b0d7f5250903f19b0d9cea67d446e7d44c8dcc071

test:
  secret_key_base: 76750c62478521dd49d5ba5ff9e910f6d972e29ec8a48bc394040de7c7644946e8887c8e51bddfbf7a0fe2e8256a05b981d0529d6ca85936758fdab1496b443e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
